### ISSUE TITLE
Why are not all types stored in one list?

### ISSUE THREAD

**Issue by mayisa87** [LauritsCSB/WineApp#1]
https://github.com/LauritsCSB/WineApp/blob/e381094e8caff16ebf0d20b2599b8b673f17a01c/WineApp/Soil/SoilDefaults.cs#L5C8-L5C8

Is there a reason why the soil types are split up and stored in differenr lists?

**Comment by LauritsCSB** [comment]
I spoke with florian about this. The reason is that, that was how i found the data. It has been changed to a single list.
