### ISSUE TITLE
Use usings

### ISSUE THREAD

**Issue by mayisa87** [LauritsCSB/WineApp#3]
https://github.com/LauritsCSB/WineApp/blob/e381094e8caff16ebf0d20b2599b8b673f17a01c/WineApp/Terroir.cs#L24

To avoid typing always the whole namespace, you can use usings. Rewatch this video:
https://course.raketementoring.com/courses/1987161/lectures/45651791

**Comment by LauritsCSB** [comment]
I changed the namespaces, thanks for linking the lesson!
