### ISSUE TITLE
How will you know the month?

### ISSUE THREAD

**Issue by mayisa87** [LauritsCSB/WineApp#5]
https://github.com/LauritsCSB/WineApp/blob/e381094e8caff16ebf0d20b2599b8b673f17a01c/WineApp/MicroClimate.cs#L8

If you add it to the list, how will you knownto which month the object belongs?

Maybe a dictionary holding the month as key value and the climate object as data would be handy here

**Comment by LauritsCSB** [comment]
The class has been removed and that field has been added to the vineyard class. Now a list holding double's, one for every month of the year representing an average value for that month.
